### ISSUE TITLE
suggestion to include workflow using this

### ISSUE THREAD

**Issue by johndpope** [ZHO-ZHO-ZHO/ComfyUI-InstantID#2]
https://github.com/civitai/civitai_comfy_nodes
![Screenshot from 2024-01-23 10-49-38](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/289994/f96fb699-5c3d-427c-b2ad-f177e5af580a)

**Comment by ameen-roayan** [comment]
A workflow sample would be great if someone figures this out

**Comment by johndpope** [comment]
Thank you @ZHO-ZHO-ZHO 
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/tree/main/INSTANTID%20WORKFLOWS


the readme needs update that there are dependencies on custom_nodes
![Screenshot from 2024-01-24 09-39-30](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/289994/8720e680-ee9d-4978-9400-31ebc2874a0f)


so far I've determined these

```shell
custom_nodes
gh repo clone ZHO-ZHO-ZHO/ComfyUI-ArtGallery
gh repo clone ZHO-ZHO-ZHO/ComfyUI-Layout-Zh-Chinese
```
