### ISSUE TITLE
请问 'str' object has no attribute 'shape' 报错怎么解决？

### ISSUE THREAD

**Issue by bingal** [ZHO-ZHO-ZHO/ComfyUI-InstantID#20]
Error occurred when executing PreviewImage:

'str' object has no attribute 'shape'

File "/home/bingal/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/bingal/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/bingal/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/bingal/ComfyUI/nodes.py", line 1359, in save_images
full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
^^^^^^^^^^^^^^^

**Comment by xnmt9** [comment]
Were you able to figure this out?

**Comment by bingal** [comment]
Not resolved yet, tested a few workflows within the project and they all report the same error.

**Comment by bingal** [comment]
<img width="1185" alt="image" src="https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/2054962/0a8f4813-09bd-4e15-97e4-aa2c0658668d">
2.0的workflow也不行，😖

**Comment by bingal** [comment]
The issue has been identified; it seems to be a problem with the image I inputted. I’m not sure if it’s the size ratio or the photo resolution being too high. However, when I replaced it with an AI-generated 1024x1024 image, it worked. The main problem is that the error message is very unclear, and there are no other error messages in the console.
