### ISSUE TITLE
Error Trying to use workflow... If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by trashie65** [ZHO-ZHO-ZHO/ComfyUI-InstantID#50]
after intall and trying to use 1 of your v2 workflows i get this error...

raise OSError(
OSError: Unable to load weights from checkpoint file for 'D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\checkpoints\controlnet\ControlNetModel_config.json' at 'D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\checkpoints\controlnet\ControlNetModel_config.json'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by NolenBrolen** [comment]
I fixed this by changing the backslashed to forward slashes. so change it from '''D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\checkpoints\controlnet\ControlNetModel_config.json''' to '''D:/ComfyUI_windows_portable_nvidia_cu118_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-InstantID/checkpoints/controlnet/ControlNetModel_config.json'''
