### ISSUE TITLE
INSIGHTFACE ERROR

### ISSUE THREAD

**Issue by lunatico67** [ZHO-ZHO-ZHO/ComfyUI-InstantID#59]
Failed to validate prompt for output 12:
* IDGenerationNode 15:
  - Return type mismatch between linked nodes: insightface, INSIGHTFACE != INSIGHTFACEMODEL
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

**Comment by GPU-server** [comment]
Found it @lunatico67 ?
