### ISSUE TITLE
ValueError: With local_files_only set to False, you must first locally save the text_encoder_2 and tokenizer_2 in the following path: laion/CLIP-ViT-bigG-14-laion2B-39B-b160k with `pad_token` set to '!'.

### ISSUE THREAD

**Issue by by517840374** [ZHO-ZHO-ZHO/ComfyUI-InstantID#79]
ValueError: With local_files_only set to False, you must first locally save the text_encoder_2 and tokenizer_2 in the following path: laion/CLIP-ViT-bigG-14-laion2B-39B-b160k with `pad_token` set to '!'.

这个什么问题，有人知道吗？

**Comment by shaaaaron** [comment]
我遇到了相同的问题，请问你知道该怎么解决吗？

**Comment by by517840374** [comment]
> 我遇到了相同的问题，请问你知道该怎么解决吗？

需要科学上网，他需要在huggingface下载点东西

**Comment by oftenliu** [comment]
@by517840374 下载下来的文件夹放在哪里呢

**Comment by shaaaaron** [comment]
> @by517840374 下载下来的文件夹放在哪里呢

到diffusers库代码里面，将线上路径改成文件所在的本地路径。我用的from_single_file加载，需要修改diffusers/loaders/single_file.py和single_file_utils.py文件。
