### ISSUE TITLE
无法使用本地模型

### ISSUE THREAD

**Issue by youcanyoubing** [ZHO-ZHO-ZHO/ComfyUI-InstantID#91]
执行IDBaseModelLoader_local时出错：

HTTPSConnectionPool（host='raw.githubusercontent.com'， port=443）：超出最大重试次数，网址：/Stability-AI/generative-models/main/configs/inference/sd_xl_base.yaml（由 SSLError（SSLCertVerificationError（1， '[SSL： CERTIFICATE_VERIFY_FAILED] certificate verify failed： unable to get local issuer certificate （_ssl.c：997）'）））

文件“C：\ComfyUI_windows_portable\ComfyUI\execution.py”，第 152 行，recursive_execute
output_data， output_ui = get_output_data（obj， input_data_all）
文件“C：\ComfyUI_windows_portable\ComfyUI\execution.py”，第 82 行，get_output_data
return_values = map_node_over_list（obj， input_data_all， obj.函数，allow_interrupt=True）
文件“C：\ComfyUI_windows_portable\ComfyUI\execution.py”，第 75 行，map_node_over_list
results.append（getattr（obj， func）（**slice_dict（input_data_all， i）））
文件“C：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py”，第 158 行，load_model
管道 = StableDiffusionXLInstantIDPipeline.from_single_file（
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\loaders.py”，第 2308 行，from_single_file
管道 = download_from_original_stable_diffusion_ckpt（
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py”，第 1289 行，download_from_original_stable_diffusion_ckpt
original_config_file = BytesIO（requests.get（config_url）.content）
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\api.py”，第 73 行，在 get 中
返回请求（“get”， url， params=params， **kwargs）
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\api.py”，第 59 行，在请求中
返回 session.request（method=method， url=url， **kwargs）
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\sessions.py”，第 589 行，在请求中
resp = self.send（prep， **send_kwargs）
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\sessions.py”，第 703 行，在发送中
r = adapter.send（request， **kwargs）
文件“C：\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\adapters.py”，第 517 行，在发送中
提高 SSLError（e， request=request）

**Comment by cyz6668** [comment]
请问这到底是什么问题呢

**Comment by zhd2337133525** [comment]
怎么解决

**Comment by youcanyoubing** [comment]
不知道什么使用这个本地模型依旧需要在拥抱脸上下东西，正常是连不上的所以报错，我把那些东西全下载下来就好了

**Comment by cyz6668** [comment]
> 不知道什么使用这个本地模型依旧需要在拥抱脸上下东西，正常是连不上的所以报错，我把那些东西全下载下来就好了

这个下载放在哪里

**Comment by youcanyoubing** [comment]
> > 不知道什么使用这个本地模型依旧需要在拥抱脸上下东西，正常是连不上的所以报错，我把那些东西全下载下来就好了
> 
> 这个下载放在哪里

有个sd_xl_base.yaml可以放到本地，然后找找有个人的方法代理到本地读取，还有几个比较大的文件是你的用户名/. cache里面，具体还是要看报错提示，然后在那个文件夹里找找有没有系统刚刚建立的文件夹，你要按那个文件夹的名字在拥抱脸上把文件下下来放里面，或者你有梯子的话挂梯子跑图，这些会自动下载的
